# Generated by Django 2.2 on 2022-04-26 18:23

import django.contrib.auth.base_user
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.TextField()),
                ('username', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(null=True)),
                ('phone', models.TextField(default='n/a')),
                ('license', models.TextField()),
                ('img_license_front_url', models.TextField(default='n/a')),
                ('img_license_back_url', models.TextField(default='n/a')),
                ('img_url', models.TextField(default='n/a')),
                ('background_img_url', models.TextField(default='n/a')),
                ('verified_identity', models.BooleanField(default=False)),
                ('background_check_status', models.TextField(default='n/a')),
                ('quality_rank', models.FloatField(default=0.0)),
                ('timestamp', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django.contrib.auth.base_user.BaseUserManager),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('auction', models.BooleanField(null=True)),
                ('product_type', models.TextField(default='n/a')),
                ('contract_type', models.TextField(default='n/a')),
                ('service_type', models.TextField(default='n/a')),
                ('data_type', models.TextField(default='n/a')),
                ('season', models.TextField(default='n/a')),
                ('views', models.IntegerField(default=0)),
                ('img_url', models.TextField(default='n/a')),
                ('address', models.TextField(default='n/a')),
                ('address_2', models.TextField(default='n/a')),
                ('city', models.TextField(default='n/a')),
                ('zip_code', models.TextField(default='n/a')),
                ('state', models.TextField(default='n/a')),
                ('country', models.TextField(default='n/a')),
                ('dob', models.TextField(default='n/a')),
                ('duration_timestamp', models.TextField(default='n/a')),
                ('timestamp', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.User')),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('timestamp', models.TextField()),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.Store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.User')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuation_timestamp', models.TextField()),
                ('termination_timestamp', models.TextField()),
                ('img_url', models.TextField(default='n/a')),
                ('address', models.TextField(default='n/a')),
                ('timestamp', models.TextField()),
                ('stakeholder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.Stakeholder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.User')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('timestamp', models.TextField()),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_follower_id', models.IntegerField()),
                ('timestamp', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.User')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_follower_id', models.IntegerField()),
                ('timestamp', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.User')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_bid', models.BooleanField(null=True)),
                ('accepted_bid', models.BooleanField(null=True)),
                ('application', models.BooleanField(null=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('timestamp', models.TextField()),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.Store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.User')),
            ],
        ),
    ]
