# Generated by Django 3.2.5 on 2022-01-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='auction',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='contract_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='data_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='duration_timestamp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='product_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='season',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='service_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='img_url',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('timestamp', models.TextField()),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('continuation_timestamp', models.TextField()),
                ('termination_timestamp', models.TextField()),
                ('img_url', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('timestamp', models.TextField()),
                ('stakeholder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.stakeholder')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('timestamp', models.TextField()),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.store')),
            ],
        ),
    ]
