# Generated by Django 2.2 on 2022-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='duration_start_timestamp',
            field=models.TextField(default='n/a'),
        ),
    ]
