# Generated by Django 2.2 on 2022-05-02 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_duration_start_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='minimum_bid',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('auction', models.BooleanField(null=True)),
                ('season', models.TextField(default='n/a')),
                ('img_url', models.TextField(default='n/a')),
                ('address', models.TextField(default='n/a')),
                ('address_2', models.TextField(default='n/a')),
                ('city', models.TextField(default='n/a')),
                ('zip_code', models.TextField(default='n/a')),
                ('state', models.TextField(default='n/a')),
                ('country', models.TextField(default='n/a')),
                ('timestamp', models.TextField()),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.User')),
            ],
        ),
    ]
