# Generated by Django 3.2.5 on 2022-01-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220126_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
