# Generated by Django 3.2.5 on 2022-01-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='duration_timestamp',
            field=models.TextField(default=' '),
        ),
    ]
