# Generated by Django 2.2 on 2022-05-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220502_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='minimum_bid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.FloatField(),
        ),
    ]
