# Generated by Django 3.2.5 on 2022-01-26 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_store_duration_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='address',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='img_url',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='store',
            name='contract_type',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='store',
            name='data_type',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='store',
            name='duration_timestamp',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='store',
            name='img_url',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_type',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='store',
            name='season',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='store',
            name='service_type',
            field=models.TextField(default='n/a'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_follower_id', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.user')),
            ],
        ),
    ]
