# Generated by Django 3.2.5 on 2022-01-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220126_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_check_status',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='user',
            name='img_license_back_url',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='user',
            name='img_license_front_url',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='user',
            name='img_url',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_identity',
            field=models.BooleanField(default=False),
        ),
    ]
