# Generated by Django 3.2.5 on 2022-01-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220127_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quality_rank',
            field=models.FloatField(default=0.0),
        ),
    ]
