# Generated by Django 3.2.5 on 2022-02-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220209_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address_2',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='store',
            name='zip_code',
            field=models.TextField(default='n/a'),
        ),
    ]
