# Generated by Django 3.2.5 on 2022-02-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220210_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='dob',
            field=models.TextField(default='n/a'),
        ),
    ]
