# Generated by Django 3.2.5 on 2022-02-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_store_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_img_url',
            field=models.TextField(default='n/a'),
        ),
    ]
