# Generated by Django 3.2.5 on 2022-02-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_user_background_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(default='n/a'),
        ),
    ]
