# Generated by Django 3.2.5 on 2022-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220213_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(null=True),
        ),
    ]
