# Generated by Django 3.2.5 on 2022-04-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='timestamp',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='timestamp',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_follower_id', models.IntegerField()),
                ('timestamp', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.user')),
            ],
        ),
    ]
